# -*- coding: utf-8 -*-
"""FinalProjeDecisionTrees.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qnd1VH05AoiAdYQ0LVSSmbGGsDhEVg5C
"""

# # Decison Tree Classification
# Decision Trees sınıflandırma algoritması ile CV'lerden alınan bilgilerden tahminleme yapmayı Öğreneceğiz
# İlk olarak verilerimizi yüklüyoruz ve kütüphaneleirmizi import ediyoruz.

import numpy as np
import pandas as pd
from sklearn import tree

df = pd.read_csv("/content/sample_data/DecisionTreesClassificationDataSet.csv")

df.head()

#
# scikit-learn kütüphanesi decision tree'lerin düzgün çalışması için herşeyin rakamlsal olmasını bekliyor bu nedenle
# veri setimizdeki tüm Y ve N değerlerini 0 ve 1 olarak düzeltiyoruz.
# Aynı sebeple eğitim seviyesini de BS:0 MS:1 ve PhD:2 olarak güncelliyoruz.
# map() kullanarak boş hücreler veya geçersiz değer girilen hücreler NaN ile doldurulacaktır, buna şuandaki veri setimizde ihtiyacıkız yok ama sizin ilerde yoğun veri ile çalıştığınız zaman ihtiyacınız olacaktır.
#

duzetme_mapping = {'Y': 1, 'N': 0}

df['IseAlindi'] = df['IseAlindi'].map(duzetme_mapping)
df['SuanCalisiyor?'] = df['SuanCalisiyor?'].map(duzetme_mapping)
df['Top10 Universite?'] = df['Top10 Universite?'].map(duzetme_mapping)
df['StajBizdeYaptimi?'] = df['StajBizdeYaptimi?'].map(duzetme_mapping)
duzetme_mapping_egitim = {'BS': 0, 'MS': 1, 'PhD': 2}
df['Egitim Seviyesi'] = df['Egitim Seviyesi'].map(duzetme_mapping_egitim)
df.head()

# Sonuc sütununu ayırıyoruz:

y = df['IseAlindi']
z = df.drop(['IseAlindi'], axis=1)


z.head()

# Decision Tree'mizi oluşturuyoruz:

clf = tree.DecisionTreeClassifier()
clf = clf.fit(z,y)

# Prediction yapalım şimdi
# 5 yıl deneyimli, hazlihazırda bir yerde çalışan ve 3 eski şirkette çalışmış olan, eğitim seviyesi Lisans
# top-10-üniversiteden mezunu değil

print(clf.predict([[5, 1, 3, 0, 0, 0]]))

# Toplam 2 yıllık iş deneyimi, 7 kez iş değiştirmiş çok iyi bir okul mezunu şuan çalışmıyor
print (clf.predict([[2, 0, 7, 0, 1, 0]]))



# Toplam 2 yıllık iş deneyimi, 7 kez iş değiştirmiş çok iyi bir okul mezunu değil şuan çalışıyor
print (clf.predict([[2, 1, 7, 0, 0, 0]]))



# Toplam 20 yıllık iş deneyimi, 5 kez iş değiştirmiş iyi bir okul mezunu şuan çalışmıyor
print (clf.predict([[20, 0, 5, 1, 1, 1]]))