# -*- coding: utf-8 -*-
"""K-enyakin-komsu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sILCSjjZurmXjF4esgGPG6n609ScX-re
"""

# k en yakın komşu ile sınıflandırma işlemi
import math

x1 = [2, 3, 3, 4, 5, 6, 7, 9, 11, 10]
x2 = [4, 6, 4, 10, 8, 3, 9, 7, 7, 2]
sinif = ["kötü", "iyi", "iyi", "kötü", "kötü", "iyi", "iyi", "kötü", "kötü", "kötü"]

deger1 = float(input("Değer 1 i girin :"))
deger2 = float(input("Değer 1 i girin :"))
k = int(input("K değerini giriniz"))

di = {}

for i in range(len(x1)):
  deger1fark = x1[i]-deger1
  deger2fark = x2[i]-deger2
  u = math.sqrt(math.pow(deger1fark, 2) + math.pow(deger2fark, 2))
  di.update({i:u})

print(di)
dis = {k: v for k, v in sorted(di.items(), key=lambda item: item[1])}
print(dis)

for i in dis:
  print(x1[i]," ",x2[i]," ",i," ",sinif[i]," ",dis[i])

dis_list = list(dis)

kotu = iyi = 0
k_list = []
for i in range(k):
  k_list.append(sinif[dis_list[i]])


print(k_list)
kotu = iyi = 0
kotu = k_list.count("kötü")
iyi = k_list.count("iyi")

if iyi>kotu:
  print("Sınıflandırma sonucu = İYİ")
else:
  print("sınıflandırma sonucu KÖTÜ")