# -*- coding: utf-8 -*-
"""ML-NaiveBayes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aLdNj8Hyf9HrmtJn1zIwHfYfWsl_9RGA

#İlk önce numpy kütüphanesini projeye dahil ettik
#ardından Sklearn kütüphanesi ile Naive Bayes kütüphanesini aldık
"""

import numpy as np
from sklearn.naive_bayes import GaussianNB

"""Kırmızıya 0 - Sarıya 1, Spora 0 - SUVa 1, Yerliye 0 İthale 1 değerlerini veriyorum"""

# Burada özelliklerimize sayısal değerler atadık ve bunları bir dizide matris halinde tuttum
X = np.array([
              [0, 0, 0],
              [0, 0, 0],
              [0, 0, 0],
              [1, 0, 0],
              [1, 0, 1],
              [1, 1, 1],     #6
              [1, 1, 1],     #7
              [1, 1, 0],
              [0, 1, 1],
              [0, 0, 1]     #10

])# Burada da evet ve hayır durumlarını tanımlıyorum
Y = np.array([1, 0, 1, 0, 1, 0, 1, 0, 0, 1])

# Model değişkenine Naive bayes referansını ekliyoruz ardından model içinde x ve y yi fit ediyoruz.
model = GaussianNB()
model.fit(X, Y)

# burada da test edeceğimiz verileri giriyoruz
print(model.predict([[0, 1, 1]]))